@startuml Manage Auth (Logout)

header Massage Reservation System
footer Page %page% of %lastpage%
title "Manage Auth (Logout)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth

client->server ++:req.get('/auth/logout')
server->routerAuth ++:app.use('/auth/logout',auth)
routerAuth -> controllersAuth ++:logout()
controllersAuth->client --:response

@enduml