@startuml Manage Reservation (POST)

header Massage Reservation System
footer Page %page% of %lastpage%
title "Manage Reservation (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservations
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationsDatabase

client->server ++:req.post('/reservations')
server->routerReservations ++:app.use('/reservations',reservations)
routerReservations -> controllersReservations ++:createReservation()
controllersReservations->modelReservation ++:create(req.body)
modelReservation ->ReservationsDatabase ++: ReservationSchema
ReservationsDatabase --> modelReservation --: reservation
controllersReservations <-- modelReservation --:reservation
controllersReservations->client --:response

@enduml