@startuml Manage MassageShop (Delete)


header MassageShop Sequence Diagram
footer Page %page% of %lastpage%
title "Manage MassageShop (Delete)"


participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:massageShop" as routerMassageShops
participant "<<controllers>>\n:massageShop" as controllersMassageShops
participant "<<model>>\n:MassageShop" as modelMassageShop
database "<<MongoDB>>\n:massageShop" as MassageShopsDatabase


client->server ++:req.delete('/massageShops/:id')
server->routerMassageShops ++:app.use('/massageShops',massageShop)
routerMassageShops -> controllersMassageShops ++:protect, authorize("admin"), deleteMassageShop()
controllersMassageShops->modelMassageShop ++:massageShop.deleteOne()
MassageShopsDatabase --> modelMassageShop --: massageShop
controllersMassageShops <-- modelMassageShop --:massageShop
controllersMassageShops->client --:response


@enduml